import type { Metadata } from "next";
import { Poppins } from 'next/font/google'
import { Montserrat } from 'next/font/google'
import "./globals.css";

export const metadata: Metadata = {
  title: "Physio Manager",
  description: "Generated by create next app",
};

const poppins = Poppins({
  weight: ['200','400','500','600','700'],
  subsets: ["latin","latin-ext"]
})
const montserrat = Montserrat({
  weight: "variable",
  subsets: ["latin","latin-ext"]
})

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${poppins.className}`}>
        {children}
      </body>
    </html>
  );
}
