import { Toaster } from "@/components/ui/sonner";
import { Analytics } from "@vercel/analytics/next";
import type { Metadata } from "next";
import { Poppins } from 'next/font/google';
import "./globals.css";

export const metadata: Metadata = {
  title: "Physio Manager",
  description: "Generated by create next app",
};

const poppins = Poppins({
  weight: ['200', '400', '500', '600', '700'],
  subsets: ["latin", "latin-ext"]
})

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${poppins.className} relative w-content bg-[#F6F5F2]`}>
          <div className="max-h-dvh overflow-auto w-full">
            {children}
          </div>
        <Toaster position="top-right"/>
        <Analytics />
      </body>
    </html>
  );
}
