import type { Metadata } from "next";
import { Poppins } from 'next/font/google'
import "./globals.css";
import Navbar from '@/components/Navbar';
import { UseClientProvider } from '@/hooks/useClientProvider';
import { Toaster } from "@/components/ui/sonner";
import { ReactQueryDevtools } from '@tanstack/react-query-devtools'

export const metadata: Metadata = {
  title: "Physio Manager",
  description: "Generated by create next app",
};

const poppins = Poppins({
  weight: ['200', '400', '500', '600', '700'],
  subsets: ["latin", "latin-ext"]
})

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${poppins.className} relative flex md:h-fit  w-content bg-[#F6F5F2]`}>
        <Navbar />
        <UseClientProvider>
          <div className="max-h-[calc(100dvh-80px)] lg:max-h-dvh overflow-auto w-full">
            {children}
          </div>
           <ReactQueryDevtools initialIsOpen={false} />
        </UseClientProvider>
        <Toaster position="top-right"/>
      </body>
    </html>
  );
}
